### ISSUE TITLE
The highlighting of the word that is being read now - for Russian lang

### ISSUE THREAD

**Issue by perdolka** [ettoolong/TTSFox#11]

**Comment by ettoolong** [comment]
Support in version 0.0.19.

**Comment by perdolka** [comment]
Thank you!
Do you have some technical reasons to not support Firefox 55 ?

**Comment by ettoolong** [comment]
There are too many compatibility issues to support old Firefox version.

I think this is the main issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1338898
the workaround: use content-script to get selection text,
content-script can't work on some pages. e.g.: **addons.mozilla.org**, **about:home**

Other compatibility issues:
1. Before Firefox 49, you need set **media.webspeech.synth.enabled** to **true**(in **about:config**), and restart Firefox to enable SpeechSynthesis APIs.
see: https://github.com/ettoolong/TTSFox/blob/0345d0ebbb25888291c886cbd688342bad1cdcf2/data/js/addon-script.js#L126-L137
Old TTSFox(v0.0.9- base on addon-SDK) auto enable SpeechSynthesis APIs and show message:
![restart firefox](https://user-images.githubusercontent.com/909570/33322965-fa453196-d485-11e7-924d-c59f19c23c73.png)
But WebExtension can't do that.
(Firefox set **media.webspeech.synth.enabled** default **true** at Firefox 49+ )

2. Some WebExtension API bugs in old Firefox version. (sorry, I can't remember all of them)
These bugs have been resolved in different Firefox version, make workaround for them is a really difficult work.

3. Some WebExtension API only support after Firefox 51+, e.g.: **browser.runtime.getBrowserInfo**

I know many users still using Firefox 52 ESR (because they need legacy add-on support).
I can try to support old Firefox version. (and hope user don't give me 1 star because they hit old Firefox bug.)

**Comment by ettoolong** [comment]
TTSFox version 0.0.20: Fix compatibility with Firefox 52~57

**Comment by perdolka** [comment]
Oh, thank you again, it`s awesome!
> But WebExtension can't do that. (restart message)
> and hope user don't give me 1 star because they hit old Firefox bug

In that case, maybe, it makes sense to add information about manual restart (only for 52, 55) into description?

**Comment by ettoolong** [comment]
The **media.webspeech.synth.enabled** default value is **true** at Firefox 49+. It's okay.
